services:
  db:
    image: postgres:latest
    container_name: compass_postgres_db
    restart: always
    
    environment:
      POSTGRES_USER: compass
      POSTGRES_PASSWORD: cmps_db_87191511
      POSTGRES_DB: cmpsdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: compass_redis_cache
    volumes:
      - data:/var/lib/redis

  grobid:
    image: lfoppiano/grobid:0.8.0
    container_name: grobid
    ports: ["8070:8070"]
    environment:
      GROBID_MAXCONNECTIONS: 20

  qdrant:
    image: qdrant/qdrant:latest
    container_name: compass_qdrant
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:    
  postgres_data:
  data:
